version: '3'
services:
  react-frontend:
    build: 
      dockerfile: Dockerfile
      context: containers/react-frontend
    ports:
      - "3000:3000"
    restart: always
  flask-backend:
    build:
      dockerfile: Dockerfile
      context: containers/flask-backend
    env_file: .env-flask
    ports:
      - "5000:5000"
    restart: always
  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env-mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci