apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  type: ClusterIP
  ports: 
  - name: "mysql"
    protocol: "TCP"
    port: 3306
    targetPort: 3306
  selector:
    tier: mysql-database

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: ebs-gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database
spec:
  replicas: 1
  selector: 
    matchLabels:
      tier: mysql-database
  template:
    metadata:
      labels:
        tier: mysql-database
    spec:
      containers:
        - name: mysql-database-container
          image: mysql/mysql-server:5.7
          args:
            - "--ignore-db-dir=lost+found"
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-dynamic-deploy-volume
            mountPath: /var/lib/mysql
          env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: 'yes'
          - name: MYSQL_DATABASE
            value: 'kilnwiki_db' # 変更不可。いまはflaskのconfig.pyに同DB名がハードコーディングされている。
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-auth
                key: mysql_user_name
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-auth
                key: mysql_password
          resources:
            limits:
              memory: "1280Mi"
              cpu: "1"
            requests:
              memory: "640Mi"
              cpu: 300m
      volumes: 
      - name: mysql-dynamic-deploy-volume
        persistentVolumeClaim:
          claimName: mysql-pvc