apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  type: LoadBalancer
  ports: 
  - name: "react-on-nginx"
    protocol: "TCP"
    port: 8085
    targetPort: 80
  selector:
    tier: react-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 2
  selector: 
    matchLabels:
      tier: react-frontend
  template:
    metadata:
      labels:
        tier: react-frontend
    spec:
      containers:
        - name: react-frontend-container
          image: mice74yamada/kilnwiki-frontend
          ports:
          - containerPort: 80
          env:
          - name: NGINX_RESOLVER_NAME
            value: "kube-dns.kube-system.svc.cluster.local valid=5s"
          resources:
            limits:
              memory: "1280Mi"
              cpu: "1"
            requests:
              memory: "640Mi"
              cpu: 300m