apiVersion: v1
kind: Service
metadata:
  name: mysql-database-clusterip
spec:
  type: ClusterIP
  ports: 
  - name: "mysql"
    protocol: "TCP"
    port: 3306
    targetPort: 3306
  selector:
    tier: mysql-database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database
spec:
  replicas: 1
  selector: 
    matchLabels:
      tier: mysql-database
  template:
    metadata:
      labels:
        tier: mysql-database
    spec:
      containers:
        - name: mysql-database-container
          image: mysql/mysql-server:5.7
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: 'yes'
          - name: MYSQL_DATABASE
            value: 'kilnwiki_db' # 変更不可。いまはflaskのconfig.pyに同DB名がハードコーディングされている。
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-auth
                key: mysql_user_name
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-auth
                key: mysql_password
          resources:
            limits:
              memory: "1280Mi"
              cpu: "1000m"
---