apiVersion: v1
kind: Service
metadata:
  name: react-frontend-loadbalancer
spec:
  type: LoadBalancer
  ports: 
  - name: "react-on-nginx"
    protocol: "TCP"
    port: 8085
    targetPort: 80
  selector:
    tier: react-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      tier: react-frontend
  template:
    metadata:
      labels:
        tier: react-frontend
    spec:
      containers:
        - name: react-frontend-container
          image: mice74yamada/kilnwiki-frontend
          ports:
          - containerPort: 80
          env:
          - name: NGINX_RESOLVER_NAME
            value: kilnwiki.svc.cluster.local #[TODO] 動的に内部DNS名を取得する方法があれば、それを採用する
          resources:
            limits:
              memory: "1280Mi"
              cpu: "1000m"