"""removed description column

Revision ID: 2d1c0e642387
Revises: 9304b28730d0
Create Date: 2021-12-08 19:56:07.508896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d1c0e642387'
down_revision = '9304b28730d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('description', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
