"""corrected misspell 'desctiption'

Revision ID: 9304b28730d0
Revises: f16c11625cc1
Create Date: 2021-11-27 15:56:06.699015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9304b28730d0'
down_revision = 'f16c11625cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('description', sa.String(length=128), nullable=True))
    op.drop_column('page', 'desctiption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('desctiption', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('page', 'description')
    # ### end Alembic commands ###
