"""comment on migration

Revision ID: dfe1b99dacd7
Revises: f15cd8455e39
Create Date: 2021-12-24 00:02:42.735168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfe1b99dacd7'
down_revision = 'f15cd8455e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page_tag_map', 'page_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('page_tag_map', 'tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_unique_constraint(None, 'page_tag_map', ['page_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page_tag_map', type_='unique')
    op.alter_column('page_tag_map', 'tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('page_tag_map', 'page_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
