"""removed update_at from page_tag_map which is not used

Revision ID: f15cd8455e39
Revises: 537aeb5fa345
Create Date: 2021-12-22 21:57:12.876558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f15cd8455e39'
down_revision = '537aeb5fa345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_tag_map', 'created_at')
    op.drop_column('page_tag_map', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_tag_map', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('page_tag_map', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
