"""initial migration

Revision ID: f16c11625cc1
Revises: 
Create Date: 2021-11-24 23:27:16.212917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16c11625cc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('desctiption', sa.String(length=128), nullable=True))
    op.add_column('page', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('page', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('page', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('page', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'updated_at')
    op.drop_column('page', 'created_at')
    op.drop_column('page', 'edited_at')
    op.drop_column('page', 'published_at')
    op.drop_column('page', 'desctiption')
    # ### end Alembic commands ###
